### ISSUE TITLE
File upload display slightly truncated on STM32F0 Discovery

### ISSUE THREAD

**Issue by techman-001** [Crest/swdcom#3]
During upload, "swd2 < file.fs" the xterm shows the file uploading normally but each file uploaded only shows up to about the last 10 lines, i.e. the file upload display is truncated by around 10 lines at the end.

The file is uploaded properly however, only the display of the upload is truncated. When the upload is complete and I run "swd2" I can see the truncated lines missing earlier.

Todays GIT pull used (stlink flash display process is fixed, thanks!)
Freebsd 11.2
STM32F0 Disco

Example uploading 2mhz.fs
-------------------------------------
>% swd2 < 72mhz.fs 
compiletoflash  ok'
  ok'
: 72mhz ( -- )        \ set STM32F103 clock to 72 MHz  ok'
  $12 $40022000 !       \ two flash mem wait states  ok'
  1 16 lshift  $40021000 bis! \ set HSEON  ok'
  begin 1 17 lshift $40021000   ok'
      bit@ until       \ wait for HSERDY  ok'
  1 16 lshift        \ HSE clock is 8 MHz Xtal source for PLL  ok'
  7 18 lshift or       \ PLL factor: 8 MHz * 9 = 72 MHz = HCLK  ok'
  4  8 lshift or       \ PCLK1 = HCLK/2 = 36MHz tp@gronk:~/mecrisp-stellaris/f0-swdcom%

Running swd2, now can see the balance of the contents of 72mhz.fs.  
--------------------------------------------------------------------------------------------

>% swd2
 ok'
  2 14 lshift or       \ ADCPRE = PCLK2/6  ok'
  2 or $40021004  !       \ PLL is the system clock  ok'
  1 24 lshift $40021000 bis!  \ set PLLON  ok'
  begin 1 25 lshift $40021000   ok'
      bit@ until       \ wait for PLLRDY  ok'
;  ok'
  ok'
compiletoram  ok.
  ok.
72mhz  ok.

**Comment by Crest** [comment]
The swd2 tool is working as intended. It reads all input (until end of file) from standard input and sends it to the target before it exits. It has no way of known when the target has processed all input and produced all output.

There are already other solutions if you want the target to terminate swd2 after it's done e.g. to hexdump the flash, but it would be easy to add a flag to ignore end of file on standard input.

**Comment by Crest** [comment]
Solved via IRC. The swd2 prototype code is quirky and the user was "holding wrong" assuming it to have less annoyingly sharp edges.
