### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by sbobyrne** [Crest/swdcom#8]
I get the following error when I try to compile swdcom from github using make:

[ -d stlink/.git ] || git submodule update --init
Submodule 'stlink' (https://github.com/Crest/stlink.git) registered for path 'stlink'
Cloning into '/home/sean/Downloads/swdcom/swdcom/stlink'...
Submodule path 'stlink': checked out '14fc947acfcd04dd2a07c26d0ce7ea7916b2a65c'
make -C stlink
make[1]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink'
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.33.0") 
-- Rewrite /home/sean/Downloads/swdcom/swdcom/stlink/.version with 1.6.1!
-- stlink version: 1.6.1-91-g14fc947
-- Major 1 Minor 6 Patch 1
-- Performing Test C_SUPPORTS_STD_GNU11
-- Performing Test C_SUPPORTS_STD_GNU11 - Success
-- Performing Test C_SUPPORTS_STD_GNU18
-- Performing Test C_SUPPORTS_STD_GNU18 - Success
-- Performing Test C_SUPPORTS_WALL
-- Performing Test C_SUPPORTS_WALL - Success
-- Performing Test C_SUPPORTS_WEXTRA
-- Performing Test C_SUPPORTS_WEXTRA - Success
-- Performing Test C_SUPPORTS_WSHADOW
-- Performing Test C_SUPPORTS_WSHADOW - Success
-- Performing Test C_SUPPORTS_D_FORTIFY_SOURCE_2
-- Performing Test C_SUPPORTS_D_FORTIFY_SOURCE_2 - Success
-- Performing Test C_SUPPORTS_FSTRICT_ALIASING
-- Performing Test C_SUPPORTS_FSTRICT_ALIASING - Success
-- Performing Test C_SUPPORTS_WUNDEF
-- Performing Test C_SUPPORTS_WUNDEF - Success
-- Performing Test C_SUPPORTS_WFORMAT
-- Performing Test C_SUPPORTS_WFORMAT - Success
-- Performing Test C_SUPPORTS_WFORMAT_SECURITY
-- Performing Test C_SUPPORTS_WFORMAT_SECURITY - Success
-- Performing Test C_SUPPORTS_WMAYBE_UNINITIALIZED
-- Performing Test C_SUPPORTS_WMAYBE_UNINITIALIZED - Success
-- Performing Test C_SUPPORTS_WMISSING_VARIABLE_DECLARATIONS
-- Performing Test C_SUPPORTS_WMISSING_VARIABLE_DECLARATIONS - Failed
-- Performing Test C_SUPPORTS_WSHORTEN_64_TO_32
-- Performing Test C_SUPPORTS_WSHORTEN_64_TO_32 - Failed
-- Performing Test C_SUPPORTS_WIMPLICIT_FUNCTION_DECLARATION
-- Performing Test C_SUPPORTS_WIMPLICIT_FUNCTION_DECLARATION - Success
-- Performing Test C_SUPPORTS_WREDUNDANT_DECLS
-- Performing Test C_SUPPORTS_WREDUNDANT_DECLS - Success
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test C_SUPPORTS_O2
-- Performing Test C_SUPPORTS_O2 - Success
-- Performing Test C_SUPPORTS_WERROR
-- Performing Test C_SUPPORTS_WERROR - Success
-- Found libusb: /usr/lib/libusb-1.0.so  
-- Looking for __stack_chk_fail in ssp
-- Looking for __stack_chk_fail in ssp - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- STLINK_LIB_SHARED: stlink
-- PROJECT_VERSION_MAJOR: 1
-- VERSION: 1.6.1
-- STLINK_LIB_STATIC: stlink-static
-- PROJECT_VERSION_MAJOR: 1
-- VERSION: 1.6.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.30
-- Found GTK3: -I/usr/include/gtk-3.0;/usr/include/pango-1.0;/usr/include/glib-2.0;/usr/lib/glib-2.0/include;/usr/include/harfbuzz;/usr/include/freetype2;/usr/include/libpng16;/usr/include/libmount;/usr/include/blkid;/usr/include/fribidi;/usr/include/cairo;/usr/include/lzo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/gio-unix-2.0;/usr/include/cloudproviders;/usr/include/atk-1.0;/usr/include/at-spi2-atk/2.0;/usr/include/dbus-1.0;/usr/lib/dbus-1.0/include;/usr/include/at-spi-2.0, gtk-3;gdk-3;z;pangocairo-1.0;pango-1.0;harfbuzz;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
-- Manpage generation disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sean/Downloads/swdcom/swdcom/stlink/build/Release
[RELEASE]
make[2]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[3]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[  2%] Building C object CMakeFiles/stlink.dir/src/common.c.o
[  5%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/chipid.c.o
[  8%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/flash_loader.c.o
[ 11%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/logging.c.o
[ 13%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/md5.c.o
[ 16%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/sg.c.o
[ 19%] Building C object CMakeFiles/stlink.dir/src/stlink-lib/usb.c.o
[ 22%] Linking C shared library lib/libstlink.so
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 22%] Built target stlink
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 25%] Building C object CMakeFiles/stlink-static.dir/src/common.c.o
[ 27%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/chipid.c.o
[ 30%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/flash_loader.c.o
[ 33%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/logging.c.o
[ 36%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/md5.c.o
[ 38%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/sg.c.o
[ 41%] Building C object CMakeFiles/stlink-static.dir/src/stlink-lib/usb.c.o
[ 44%] Linking C static library lib/libstlink.a
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 44%] Built target stlink-static
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 47%] Building C object CMakeFiles/st-flash.dir/src/st-flash/flash.c.o
[ 50%] Building C object CMakeFiles/st-flash.dir/src/st-flash/flash_opts.c.o
[ 52%] Linking C executable bin/st-flash
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 52%] Built target st-flash
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 55%] Building C object CMakeFiles/st-info.dir/src/st-info/info.c.o
[ 58%] Linking C executable bin/st-info
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 58%] Built target st-info
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[4]: Entering directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
[ 61%] Building C object CMakeFiles/st-util.dir/src/st-util/gdb-remote.c.o
[ 63%] Building C object CMakeFiles/st-util.dir/src/st-util/gdb-server.c.o
In function ‘do_connect’,
    inlined from ‘do_connect’ at /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:88:18,
    inlined from ‘serve’ at /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:1821:18:
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:92:14: error: ‘stlink_open_usb’ accessing 64 bytes in a region of size 28 [-Werror=stringop-overflow=]
   92 |         sl = stlink_open_usb(st->logging_level, st->reset, serialnumber, 0);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c: In function ‘serve’:
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:92:14: note: referencing argument 3 of type ‘char *’
In file included from /home/sean/Downloads/swdcom/swdcom/stlink/inc/stlink.h:306,
                 from /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:28:
/home/sean/Downloads/swdcom/swdcom/stlink/src/stlink-lib/usb.h:69:11: note: in a call to function ‘stlink_open_usb’
   69 | stlink_t *stlink_open_usb(enum ugly_loglevel verbose, int reset, char serial[STLINK_SERIAL_MAX_SIZE], int freq);
      |           ^~~~~~~~~~~~~~~
In function ‘do_connect’,
    inlined from ‘do_connect’ at /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:88:18,
    inlined from ‘main’ at /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:227:10:
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:92:14: error: ‘stlink_open_usb’ accessing 64 bytes in a region of size 28 [-Werror=stringop-overflow=]
   92 |         sl = stlink_open_usb(st->logging_level, st->reset, serialnumber, 0);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c: In function ‘main’:
/home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:92:14: note: referencing argument 3 of type ‘char *’
In file included from /home/sean/Downloads/swdcom/swdcom/stlink/inc/stlink.h:306,
                 from /home/sean/Downloads/swdcom/swdcom/stlink/src/st-util/gdb-server.c:28:
/home/sean/Downloads/swdcom/swdcom/stlink/src/stlink-lib/usb.h:69:11: note: in a call to function ‘stlink_open_usb’
   69 | stlink_t *stlink_open_usb(enum ugly_loglevel verbose, int reset, char serial[STLINK_SERIAL_MAX_SIZE], int freq);
      |           ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [CMakeFiles/st-util.dir/build.make:90: CMakeFiles/st-util.dir/src/st-util/gdb-server.c.o] Error 1
make[4]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[3]: *** [CMakeFiles/Makefile2:342: CMakeFiles/st-util.dir/all] Error 2
make[3]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[2]: *** [Makefile:156: all] Error 2
make[2]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink/build/Release'
make[1]: *** [Makefile:34: release] Error 2
make[1]: Leaving directory '/home/sean/Downloads/swdcom/swdcom/stlink'
make: *** [GNUmakefile:18: stlink/build/Release/lib/libstlink.a] Error 2

Any idea what I'm missing that is preventing compilation?

**Comment by sbobyrne** [comment]
Actually, I seem to be programming it through the USB ST-link, not the USB serial cable.

**Comment by Crest** [comment]
Please try the latest master branch again.

**Comment by Crest** [comment]
Close for lack of response.
